baseURL = "https://rakibulhasanmasum.github.io/elk-diary"
languageCode = "en-us"
title = "ELK Stack"
theme="archie"
copyright = "©r_hasan"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "staging my elk knowledge here, you may merge it with your knowledge branch. if any conflict arises, and you choose to keep changes from your branch only, or you decided to take both learnings please let me know."

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/rakibulhasanmasum"

# [[params.social]]
# name = "Twitter"
# icon = "twitter"
# url = "https://twitter.com/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/r_hasan/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
